[INCLUDES]
before = common.conf

[Definition]
_fs_prefix = ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+ \[(?:WARNING|NOTICE)\] \S+:\d+

failregex = %(_fs_prefix)sSIP auth (?:failure|challenge) \((?:REGISTER|INVITE|OPTIONS)\) .*from ip \[<HOST>\]$
            %(_fs_prefix)sBlocking IP <HOST>$

ignoreregex =
