[INCLUDES]
before = common.conf

[Definition]
_fs_prefix = ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+ \[WARNING\] \S+:\d+

failregex = %(_fs_prefix)sSIP auth failure \(REGISTER\) on sofia profile\[.*\] for \[.*\] from ip \[<HOST>\]$
            %(_fs_prefix)sSIP auth failure \(INVITE\) on sofia profile\[.*\] for \[.*\] from ip \[<HOST>\]$
            %(_fs_prefix)sSIP auth failure \(SUBSCRIBE\) on sofia profile\[.*\] for \[.*\] from ip \[<HOST>\]$
            %(_fs_prefix)sSIP auth challenge \(REGISTER\) on sofia profile\[.*\] for \[.*\] from ip \[<HOST>\]$
            %(_fs_prefix)sBlocking IP <HOST> to free memory$
            %(_fs_prefix)sToo many registrations from IP: <HOST>$
            %(_fs_prefix)srejecting call to \S+ \(from \S+ \[<HOST>:\d+\]\) - Authentication failed$

ignoreregex =
