[INCLUDES]
before = common.conf

[Definition]
# OpenLiteSpeed admin panel login failures (port 7080)
failregex = \[(\w+ \w+ +\d+ \d+:\d+:\d+ \d+)\] \[ERROR\] .*\[Client: <HOST>\].*Login failed.*$
            \[(\w+ \w+ +\d+ \d+:\d+:\d+ \d+)\] \[WARN\] .*\[Client: <HOST>\].*bad authentication.*$

ignoreregex =
