[INCLUDES]
before = common.conf

[Definition]
_daemon = pure-ftpd

failregex = ^%(__prefix_line)s\(?(?:SECURITY|WARNING)\)?\s*:?\s*(?:\[WARNING\]\s+)?Authentication failed for user \[.+\] from \[<HOST>\].*$
            ^%(__prefix_line)s\(?(?:SECURITY|WARNING)\)?\s*:?\s*(?:\[WARNING\]\s+)?Refused connection from <HOST>.*$
            ^%(__prefix_line)s\(?(?:INFO|WARNING)\)?\s*:?\s*(?:\[WARNING\]\s+)?Maximum number of connections from \[<HOST>\] reached.*$
            ^%(__prefix_line)s\(?ERROR\)?\s*:?\s*Could not login.*from.*\[<HOST>\].*$

ignoreregex =
